Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  # config.vm.box = "ubuntu/xenial32"
  # config.vm.box = "ubuntu/xenial64"
  # config.vm.provision "file", source: "./pubsub_example", destination: "$HOME/ros_catkin_ws/src/pubsub_example"
  # config.vm.provision "file", source: "./volatility", destination: "$HOME/volatility"
  # config.vm.provision :shell, path: "bootstrap.sh"
  # config.vm.provision :shell, path: "bootstrap_LiME.sh"
  # config.vm.synced_folder "test/", "/srv/website"
end
